/* arquivo: en.ts */
import type { Dicionario } from './pt'

/**
 * AS MESMAS VARIÁVEIS DO pt.ts, EM INGLÊS. Faltou ou sobrou uma, o app não
 * compila (`Dicionario`).
 *
 * Termo de sistema = o do livro/Shards em inglês — referencia/livro/dicionario-en-ptbr.md.
 * As descrições de regra ficam nos catálogos (2ª etapa do idioma).
 */
export const EN: Dicionario = {
  // ── palavras da ficha ─────────────────────────────────────────────
  atributos: {
    forca: 'Strength',
    velocidade: 'Speed',
    intelecto: 'Intellect',
    vontade: 'Willpower',
    consciencia: 'Awareness',
    presenca: 'Presence',
  },
  atributosAbrev: {
    forca: 'STR',
    velocidade: 'SPD',
    intelecto: 'INT',
    vontade: 'WIL',
    consciencia: 'AWR',
    presenca: 'PRE',
  },
  grupos: {
    fisica: 'Physical',
    cognitiva: 'Cognitive',
    espiritual: 'Spiritual',
  },
  recursos: {
    vida: 'Health',
    foco: 'Focus',
    investidura: 'Investiture',
    cargas: 'Charges',
    vidaAbrev: 'HEALTH',
    focoAbrev: 'FOCUS',
    investiduraAbrev: 'INVEST',
    cargasAbrev: 'CHARGES',
    dano: 'Damage',
    curar: 'Heal',
    gastar: 'Spend',
    recuperar: 'Recover',
    recarregar: 'Recharge',
  },
  nomesAbas: {
    Principal: 'Main',
    Perícias: 'Skills',
    Ações: 'Actions',
    Fabriais: 'Fabrials',
    Condições: 'Conditions',
    Radiante: 'Radiant',
    Inventário: 'Inventory',
    Talentos: 'Talents',
    Personagem: 'Character',
    Anotações: 'Notes',
  },

  // ── gerais: aparecem em mais de uma tela ────────────────────────
  geral: {
    fechar: 'Close',
    cancelar: 'Cancel',
    salvar: 'Save',
    aplicar: 'Apply',
    total: 'Total',
    menu: 'Menu',
    importarJson: 'Import JSON',
    exportarJson: 'Export to Shards',
    baixarBackup: 'Download backup',
    fichaSalva: 'Sheet saved on this device.',
    naoSalvou: 'NOT saved on this device — download a backup now.',
    backupBaixado: 'Backup downloaded — keep the file. It comes back through Import.',
    saveNaoAbriu: 'This device\'s save did not open',
    baixarDescartado: 'Download the save that did not open',
    entendi: 'Got it',
    exportado: 'Downloaded — in Shards: Files → Import JSON.',
    exportarSemSemente: 'Import the Shards JSON once before exporting.',
    importado: 'Imported: {arquivo}',
    bonusSemOrigem: 'Unidentified talent (from Shards)',
    graduacao: 'Rank',
    outrosMisc: 'Other (misc)',
    deflexao: 'Deflect',
    nenhuma: '— None —',
    adicionar: '+ Add',
    editarNome: 'Edit {nome}',
    excluirNome: 'Delete {nome}',
    removerNome: 'Remove {nome}',
    nomeTotalVer: '{nome}, total {total}. See where it comes from',
    nomeTotalAlteradoVer: '{nome}, total {total}, changed by a condition. See where it comes from',
  },

  // ── App.tsx — carregando, erro, aba em construção ───────────────
  atualizacao: {
    disponivel: 'A new version of the app is available.',
    atualizar: 'Update',
  },
  app: {
    algoQuebrou: 'something broke',
    carregandoFicha: 'loading the sheet…',
    umaCopiaFicouGuardada: 'A copy was kept on this device — download it and send it to Claude to recover. The sheet below came from the seed JSON.',
    aAbaSecaoVem: 'The {secao} tab comes next.',
    aEstruturaJaEsta: 'The structure is in place — we build one at a time.',
  },

  // ── CabecalhoFixo ───────────────────────────────────────────────
  cabecalho: {
    nvN: 'lvl {n}',
    nomeAtualMaxAlterar: '{nome} {atual} of {max}. Change',
    verCondicoesAtivas: 'See active conditions',
  },

  // ── SeletorSecao — o menu das abas ──────────────────────────────
  abas: {
    secoesFicha: 'Sheet sections',
    abaAbaAbrirMenu: '{aba} tab. Open tab menu',
    abasFicha: 'Sheet tabs',
  },

  // ── MenuEngrenagem — a ⚙ do topo ────────────────────────────────
  menu: {
    shards: 'Shards',
    confirmaImportar: 'This erases everything you changed in the app. There is no undo.',
    esteAparelho: 'This device',
    idioma: 'Language',
  },

  // ── ControleMarcos — objetivos e Ideais ─────────────────────────
  marcos: {
    desfazer: 'Undo',
    marcosHistoriaN3: 'Story milestones: {n} of 3',
    marcoK: 'Milestone {k}',
    concluir: 'Complete',
    concluido: 'Completed',
    dizerPalavras: 'Speak the Words',
    jurado: 'Sworn',
  },

  // ── ControleRecurso — o ± de Vida, Foco, Investidura e cargas ───
  recurso: {
    menos: 'Minus one',
    mais: 'Plus one',
    quantidade: 'amount',
  },

  // ── PopoverDetalhe — de onde vem um número ──────────────────────
  detalhe: {
    lesoesVezes5: {
      um: '{n} injury × −5',
      varios: '{n} injuries × −5',
    },
  },

  // ── PainelTurno — o rastreador de turno ─────────────────────────
  turno: {
    foraCombateUsarAcao: 'Out of combat — using an action only pays its cost.',
    iniciarCombate: 'Start combat',
    inicio: 'Start',
    rodadaN: 'Round {n}',
    nTotalAcoes: '{n} of {total} actions',
    reacoes: {
      um: '{n} reaction',
      varios: '{n} reactions',
    },
    rapido: 'fast',
    lento: 'slow',
    preparada: 'prepared',
    turnoRapido: 'Fast turn',
    turnoLento: 'Slow turn',
    fimCombate: 'End combat',
    encerrarManterAprimorado: 'End and keep Enhanced',
    encerrarAprimoradoAcaba: 'End (Enhanced ends)',
    encerrarTurno: 'End turn',
  },

  // ── DialogoUso — o dado rolado antes de usar a ação ─────────────
  dialogoUso: {
    role1d6DigiteApp: 'Roll 1d6 and type it in. The app adds your tier (+{n}) and heals.',
    resultado1d6: '1d6 result',
    curarN: 'Heal {n}',
    roleDadoRecuperacaoDado: 'Roll your recovery die ({dado}) and split it between Health and Focus.',
    vidaMais: 'Health +',
    focoMais: 'Focus +',
    recuperar: 'Recover',
    quantasSimboloCustaAcao: 'How many {simbolo} does the action you are preparing cost? It is held until the start of your next turn.',
    livre: 'free',
  },

  // ── aba Ações ───────────────────────────────────────────────────
  acoes: {
    ataques: 'Attacks',
    nenhumaArmaEquipadaVa: 'No weapon equipped — go to Inventory to equip one.',
    alcance: 'Range',
    acerto: 'Hit',
    dano: 'Damage',
    armaPericiaPericiaNao: '{arma}: skill "{pericia}" not found on the sheet.',
    armaCorpoACorpo: 'Melee weapon',
    armaADistancia: 'Ranged weapon',
    usar: 'Use',
    maoInabil: 'Off-hand',
    fluxos: 'Surges',
    acoesLuzTempestades: 'Stormlight Actions',
    acoes: 'Actions',
    reacoes: 'Reactions',
    fabriais: 'Fabrials',
    detalheAbaFabriais: 'details in the Fabrials tab.',
    habilidadesEspreno: 'Spren Abilities',
    daPreparada: 'from the prepared one',
    peloLivroMenosN: 'By the book, with fewer than {n} marks the GM may ask you to count your infused spheres.',
    graduacaoGDadoDado: 'Rank {g}: die {dado}, target up to {tamanho}.',
    comoUsar: 'How to use',
    guiaDesteFluxoAinda: 'This surge guide has not been transcribed yet — use the activation and cost your GM sets.',
    chamasSoTalentoTransmutar: '* Flames only with the Transmute Flames talent.',
    tamanhoMenosN: '{tamanho} −{n}',
    maisUmEfeito: '+1 effect −1',
  },

  // ── guia dos fluxos (regras/fluxos.ts) ──────────────────────────
  fluxos: {
    tituloCD: 'DC — from (row) to (column)',
    solidoCurto: 'Sol',
    organicoCurto: 'Org',
    liquidoCurto: 'Liq',
    vaporCurto: 'Vap',
    arCurto: 'Air',
    chamasCurto: 'Flam*',
    solido: 'Solid',
    organico: 'Organic',
    liquido: 'Liquid',
    vapor: 'Vapor',
    arPuro: 'Clean air',
    chamas: 'Flames*',
  },

  // ── aba Anotações ───────────────────────────────────────────────
  anotacoes: {
    novaAnotacaoTitulo: 'New Note',
    editarAnotacao: 'Edit Note',
    titulo: 'Title',
    conteudo: 'Content',
    novaAnotacao: '+ New Note',
    nenhumaAnotacaoAindaToque: 'No notes yet — tap "+ New Note" to create one.',
  },

  // ── aba Condições — condições, lesões e descanso ────────────────
  condicoes: {
    agora: 'Now',
    turnoRapido: 'Fast turn',
    naoPode: 'not allowed',
    lento: 'slow',
    reacao: 'reaction',
    nenhuma: 'none',
    movimento: 'Movement',
    periciasJaMostramAprimorado: 'Skills already include Enhanced and Exhausted in their totals; advantage and disadvantage are marked there.',
    condicoes: 'Conditions',
    outra: '+ another',
    deLesao: 'from an injury',
    n1d4Vital: '1d4 vital',
    danoTurno: 'Damage per turn',
    atributo: 'Attribute',
    lesoes: 'Injuries',
    nenhumaLesao: 'No injuries.',
    menosDia: 'One day less',
    n1Dia: '−1 day',
    dias: {
      um: '{n} day',
      varios: '{n} days',
    },
    curou: 'Healed',
    registrarLesao: '+ Record injury',
    recessoCuraDuasVezes: 'Downtime heals twice as fast: remove 2 days per day of downtime.',
    role1d20SinalN: 'Roll 1d20 {sinal} {n}',
    linhasSomeTalentoMao: '({linhas}; add talents by hand)',
    d20Rolado: 'd20 rolled',
    morteCombineMestre: 'DEATH — talk it over with the GM',
    gravidade: 'Severity',
    roleDuracao: 'Roll {duracao}:',
    efeitoVoceEscolheOu: 'Effect (you choose, or roll 1d8)',
    oFoiOpcional: 'What happened (optional)',
    registrar: 'Record',
    descanso: 'Rest',
    curto1HRole: 'Short (1 h): roll {dado} and split it between Health and Focus.',
    vidaMais: 'Health +',
    focoMais: 'Focus +',
    longo8HVida: 'Long (8 h): Health {vida} and Focus {foco}, Exhausted −1, shallow injuries heal.',
    confirmarDescansoLongo: 'Confirm long rest',
    descansoLongo: 'Long rest',
    lesaoLeveGraveConta: 'Minor/serious injuries count days, not rests — use each one’s −1 day.',
  },

  // ── aba Perícias ────────────────────────────────────────────────
  pericias: {
    graduacaoDetalhe: 'rank {n} of {casas}, plus {bonus} from talents and {semOrigem} from an unidentified source',
    vantagem: 'advantage',
    desvantagem: 'disadvantage',
    graduacao: 'rank',
    vagaAteTetoTeto: 'open slot up to the cap of {teto} (level {nivel})',
    graduacaoTalentoIsentaTeto: 'rank from a talent, exempt from the cap',
    veioShardsTalentoAinda: 'came from Shards, talent not identified yet — set it in the Talents tab. Tap the number to see where it comes from.',
  },

  // ── aba Personagem ──────────────────────────────────────────────
  personagem: {
    objetivos: 'Goals',
    apagar: 'Delete',
    manter: 'Keep',
    apagarObjetivoNome: 'Delete the goal {nome}',
    objetivoNovoMestreDeu: 'New goal (from the GM, or your own)',
    nomeObjetivoNovo: 'New goal name',
    cadaObjetivoAvancaCerca:
      'Each goal advances about one milestone per session, when the GM says so. With all 3, complete it when the scene calls for it — it need not be right away. Jot down in Notes what happened at each milestone.',
    identidade: 'Identity',
    jogador: 'Player',
    nivel: 'Level',
    ancestralidade: 'Ancestry',
    culturas: 'Cultures',
    trilhaHeroica: 'Heroic path',
    ordemRadiante: 'Radiant order',
    kitInicial: 'Starting kit',
    proposito: 'Purpose',
    obstaculo: 'Obstacle',
    personalidade: 'Personality',
    aparencia: 'Appearance',
    conexoes: 'Connections',
  },

  // ── aba Principal ───────────────────────────────────────────────
  principal: {
    atributosDefesas: 'Attributes and Defenses',
    grupoNome: '{nome} group',
    defesa: 'Defense',
    deslocamentoSentidos: 'Movement and Senses',
    movimento: 'Movement',
    alcanceSentidos: 'Senses range',
    dadoRecuperacao: 'Recovery die',
    capacidadeCarga: 'Carrying capacity',
    capacidadeLevantamento: 'Lifting capacity',
  },

  // ── aba Radiante ────────────────────────────────────────────────
  radiante: {
    nomeAindaNaoRadiante: '{nome} is not a Radiant yet.',
    aAbaPreencheQuando: 'This tab fills in once Shards brings the order and the spren bond.',
    vinculo: 'Bond',
    ordem: 'Order',
    espreno: 'Spren',
    iluminado: 'enlightened',
    alcanceVinculo: 'Bond range',
    ideais: 'Ideals',
    nIdeal: 'Ideal {n}',
    asPalavrasOuAspiracao: 'The Words (or the aspiration) of this Ideal',
    palavrasNIdeal: 'Words of Ideal {n}',
    cadaIdealObjetivo3:
      'Each Ideal is a goal of 3 story milestones. With all 3, the Words can be spoken when the scene calls for it — and the GM accepts them. The Ideal talent effects stay in Shards.',
    fluxos: 'Surges',
    graduacaoN: 'rank {n}',
  },

  formularioFabrial: {
    novoFabrial: 'New Fabrial',
    editarFabrial: 'Edit Fabrial',
    unico: 'Unique (invented)',
    padrao: 'Standard (from the table)',
    fabrial: 'Fabrial',
    efeito: 'Effect',
    livre: '— free-form (not from the book) —',
    cargasPreco: '{nome} · {cargas} charges · {preco}',
    cargasN: '{nome} · {cargas} charges',
    patamar: 'Tier {n} — {marcos} marks, bind the spren DC {cd}',
    nome: 'Name',
    nomeFabrial: 'Fabrial name',
    qualidade: 'Quality (Crafting test)',
    qualidadeOpcao: '{nome} ({resultado}) · {aprimoramentos} upgr. · {revezes} drawback',
    aprimoramentos: 'Upgrades',
    revezes: 'Drawbacks',
    doEfeito: 'From {efeito}',
    naoCabe: '(does not fit this effect)',
    caracteristicasAvancadas: 'Advanced features — cost 2 upgrades (1 with Fine Handiwork, once per item)',
    combinadoMestre: '(agreed with the GM)',
    outroCombinado: 'Other, agreed with the GM',
    cargasAtuais: 'Current charges',
    maximo: 'Maximum',
    gema: 'Gem',
    material: 'Material',
    notas: 'Notes',
  },
  fabriais: {
    padrao: 'Standard',
    unico: 'Unique',
    patamarN: 'Tier {n}',
    cargasDe: 'Charges of {nome}',
    gasto: 'Use: {gasto}',
    aprimoramentos: 'Upgrades',
    revezes: 'Drawbacks',
    gema: 'Gem: {gema}',
    material: 'Material: {material}',
    recarregarInvestidura: '+1 {carga} with Investiture ({simbolo} {n})',
    editar: '✏️ Edit',
    excluir: '🗑️ Delete',
    novoFabrial: '+ New Fabrial',
    grantormenta: '🌩️ Highstorm',
    nenhumFabrial: 'No fabrials — tap "+ New Fabrial".',
  },
  inventario: {
    gerenciar: 'Manage Inventory',
    nomeItem: 'Item name',
    categoriaExemplo: 'Category (e.g. Tool)',
    pesoKg: 'Weight (kg)',
    qtd: 'Qty',
    outros: 'Other',
    pesoCarregado: 'Carried weight',
    sobrecarregado: 'Overloaded',
    livre: 'Unencumbered',
    marcos: 'Marks',
    armas: 'Weapons',
    nenhumaArma: "No weapons came in this character's JSON.",
    item: 'Item',
    peso: 'Weight',
    equipamentos: 'Equipment',
    nenhumEquipamento: 'No equipment — use "Manage Inventory" to add some.',
    pertences: 'Belongings',
    pertencesAjuda: 'Free text, one thing per line — it is the Shards "Equipment" field, and goes back there on Export.',
  },
  talentos: {
    heroicos: 'Heroic',
    radiantes: 'Radiant',
    ancestrais: 'Ancestry',
    graduacaoBonus: '+{n} rank',
    outraDigitar: 'Other (type it)…',
    grupoCulturais: 'Cultural',
    grupoUtilidadePerito: 'Utility / Specialist (examples from the book)',
    nomeEspecialidade: 'Expertise name',
    comGraduacaoBonus: '{nome} (+{n} bonus rank)',
    naoEncontrada: '{nome} (not found on the current sheet)',
    nenhumTalento: "No talents came in this character's JSON.",
    semTraducao: '(no translation)',
    preRequisitos: 'Prerequisites: {texto}',
    semEntradaCatalogo: '(no catalog entry yet)',
  },
  // ── o que as REGRAS devolvem pra tela escrever (regras/*.ts) ────
  regras: {
    faltaFoco: 'not enough focus ({n})',
    faltaInvestidura: 'not enough Investiture ({n})',
    semCarga: 'no charge',
    umaVezPorCena: 'once per scene',
    inconsciente: 'Unconscious',
    semReacao: 'no reaction',
    foraDoTurno: 'not your turn',
    jaUsouNoTurno: 'already used this turn',
    faltamAcoes: 'not enough ▶ ({n})',
    atordoadoMenos2: 'Stunned −2 ▶',
    surpreendidoMenos1: 'Surprised −1 ▶, no fast turn',
    fimTurnoSofra: 'End of your turn: take {dano}.',
    fimTurnoSofraAflicao: 'End of your turn: take the affliction damage.',
    lembreteFocado: 'Focused: abilities that cost focus cost 1 less.',
    lembretePotencializado: 'Empowered: refill Investiture at the start of each of your turns.',
    lembreteDeterminado: 'Determined: failed a test? You may add an Opportunity (and the condition ends).',
    lembreteProstrado: 'Prone: melee attacks against you gain an advantage. Standing up costs ▷.',
    lembreteUmaMao: 'Injury: you can only use one hand.',
    avisoCargasRegra: 'By the rules, the maximum would be {regra} charges (it is {atual}).',
    avisoAprimoramentos: '{qualidade} grants {n} upgrade(s); your picks add up to {gastos}.',
    avisoRevezes: '{qualidade} grants {n} drawback(s); there are {atual}.',
    avisoNaoCabe: '{opcao} does not fit this effect (requires: {requer}).',
  },
}
